# Root wrapper around httprb
module XeroHTTP
  extend HTTP::Chainable

  # sord warn - class is probably not a type, but using anyway
  # Adds header name to filter
  # 
  # _@param_ `filter` — header name to filter, can be regex in form of string
  # 
  # _@note_ — You MUST use filtered_logging feature for this to work
  def self.add_filter: (String filter) -> class[XeroHTTP]
end